= Escrow Package Plugin
:latestRevision: 2.0.0

This plugin initialize an ESCROW package. This is a zip file of the root project.
It is possible to exclude files and directories additional for the prepared default excludes.

== Usage
To use the Gradle escrow plugin. include the following in your build script:

[source,groovy,subs="attributes"]
----
plugins {
   id 'com.intershop.gradle.escrow' version '{latestRevision}'
}

escrow {
    sourceGroup = 'publishing group of the escrow package'
}
----
This plugin can be applied only to the root project. It produces a zip package with all the sources and without
Gradle wrapper directory, which will be published to the specified repository.

== Extension
This plugin adds an extension *`escrow`* to the project.

=== Properties

[cols="17%,17%,17%,68%", width="90%, options="header"]
|===
|Property | Type | Default value | Description
|*sourceGroup* | `String` | `project.getGroup()` | Group or organization of the published ESCROW source package
|*classifier*  | `String` | 'src' | Specify the classifier of this artifact.
|*mavenPublicationName* | `String` | 'mvnEscrow' | Specify the name of the publication.

|===

[source,groovy,indent=8]
.Default exclude pattern of this plugin
----

[ "<buildDir of the root project>", "*/<buildDir of the root project>", '.gradle', '.svn', '.git', '.idea', '.eclipse', '.settings', '**/.settings/**' ]

----

This list can be manipulated with the following methods:

[cols="17%,17%,17%,68%", width="90%, options="header"]
|===
|Method       | Type   | Parameter    | Description
|*exclude*    | `void` | String       | Add an additional exclude pattern to the exclude list.
|*excludes*   | `void` | List<String> | Add all elements of the parameter list to the exclude list.
|*excludes*| `void` | List<String> | Reset the default exclude list with the parameter list.
|===

== Tasks

[cols="26%,33%,40%", width="99%, options="header"]
|===
| Task name                  | Class                              |Description
| *escrowZip* | `org.gradle.api.tasks.bundling.Zip` | Creates an escrow source package from project.
|===

== License

Copyright 2022 Intershop Communications.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
